### ISSUE TITLE
surface area of solid figure

### ISSUE THREAD

**Issue by charish-exe** [andhra21231/havefun-math-bot#1]
maybe u can add surface area of solid figures ^^
(luas permukaan bangun ruang)

**Comment by andhra21231** [comment]
hmm thats a good idea

**Comment by andhra21231** [comment]
In Progress @charish-exe

**Comment by andhra21231** [comment]
bug at cylinder. searching for problem

**Comment by andhra21231** [comment]
Done All Done For This :D
